services:
    app:
        image: todo-front-dev
        build:
            context: .
            dockerfile: dev.Dockerfile
        volumes:
            - ./:/usr/src/app
            - dev_node_modules:/usr/src/app/node_modules
        ports:
            - 5173:5173
        container_name: todo-front-dev
volumes:
    dev_node_modules:
