services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
            - ./todo-backend/mongo/production/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
            - mongo_data:/data_db
    redis:
        image: redis:8-bookworm
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis_data:/data
    server:
        build:
            context: ./todo-backend
            dockerfile: Dockerfile
        volumes:
            - ./todo-backend:/usr/src/app
            - node_modules_be:/usr/src/app/node_modules
        container_name: todo-app-backend
        ports:
            - 3000:3000
        environment:
            REDIS_URL: ${REDIS_URL}
            MONGO_URL: ${MONGO_URL}
        depends_on:
            mongo:
                condition: service_started
                restart: true
            redis:
                condition: service_started
    app:
        build:
            context: ./todo-frontend
            dockerfile: Dockerfile
        volumes:
            - ./todo-frontend:/usr/src/app
            - node_modules_fe:/usr/src/app/node_modules
        container_name: todo-app-frontend
        depends_on:
            - server
    nginx:
        image: nginx:1.20.1
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80:80
        container_name: reverse-proxy
        depends_on:
            - app
volumes:
    node_modules_fe:
    node_modules_be:
    redis_data:
    mongo_data:
