services:
    server:
        image: todo-backend-dev
        volumes:
            - app_dev:/usr/src/app
            - node_modules_dev:/usr/src/app/node_modules
        ports:
            - 3000:3000
        environment:
            - REDIS_URL=redis://redis:6379
            - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    mongo:
        image: initialized-mongo
        ports:
            - 3456:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: a2tBtcX5JSimbw7
            MONGO_INITDB_DATABASE: the_database
    redis:
        image: redis:8-bookworm
        ports:
            - 6379:6379
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis_data_dev:/data
volumes:
    redis_data_dev:
    app_dev:
    node_modules_dev:
